apiVersion: v1
kind: Pod
metadata:
  name: "goroldbilling"
  labels:
    app: "goroldbilling"
spec:
  containers:
  - name: goroldbilling
    image: gorold.azurecr.io/gorold.billing:v3
    envFrom:
      - configMapRef:
          name: goroldbilling-env
  imagePullSecrets:
    - name: goroldregistry