apiVersion: v1
kind: Pod
metadata:
  name: "goroldbilling"
  labels:
    app: "goroldbilling"
spec:
  containers:
  - name: goroldbilling
    image: rafaeljcamara/gorold.billing:v4
    envFrom:
      - configMapRef:
          name: goroldbilling-env