apiVersion: v1
kind: Service
metadata:
  name: gorold-billing-service
  namespace: default
spec:
  selector:
    app: gorold-billing-pod
  type: ClusterIP
  ports:
  - name: gorold-billing-service
    protocol: TCP
    port: 80
    targetPort: 5232

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gorold-billing-serviceaccount
  annotations:
    azure.workload.identity/client-id: df9ab768-10a1-4a4f-8a2c-67cab2248705
  labels:
    azure.workload.identity/use: "true"